### ISSUE TITLE
Name of directories misleading

### ISSUE THREAD

**Issue by we-do-it-lu** [jjacke13/nixtcloud#1]
The directories refer to r Pi4 which is misleading (this is cloud not rpi).

**Comment by jjacke13** [comment]
Maybe I should write a better description because I mention it only once in the README file. This first version is for installing Nixtcloud (NixOS with Nextcloud configured and P2P connectivity enabled) in a Raspberry Pi 4. The goal is to self-host Nextcloud. So for a start I decided to build it for a Rpi4 which a think is an affordable solution. That's why the directories are named with "Rpi". But of course i will provide very analytic instructions and documentation very soon.
